name: grocery_bullet
description: A shopping app sample that uses Provider for state management.

version: 1.17.5

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:

  cloud_firestore:

  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  font_awesome_flutter: ^8.8.1
  geolocator: ^6.0.0
  google_maps_flutter: ^0.5.27+3
  geocoder: ^0.2.1
  custom_navigation_bar: ^0.3.0
  firebase_core: ^0.5.0

  flutter:
    sdk: flutter

  # Import the provider package.
  provider: ^3.1.0

  # Import formatter for formatting doubles as currencies
  intl: ^0.16.1

  # Processes CC payments with square
  square_in_app_payments: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
