name: grocery_bullet
description: A shopping app sample that uses Provider for state management.

version: 1.17.5

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:

  cloud_firestore:

  firebase_auth: any
  google_sign_in: any
  font_awesome_flutter: ^8.8.1

  flutter:
    sdk: flutter

  # Import the provider package.
  provider: ^3.1.0

  # Import formatter for formatting doubles as currencies
  intl: ^0.15.7

  # Processes CC payments with square
  square_in_app_payments: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
